# Generated by Django 4.1 on 2022-08-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=250)),
                ("prenom", models.CharField(blank=True, max_length=250, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("telephone", models.CharField(max_length=20)),
            ],
            options={"ordering": ["nom"],},
        ),
    ]
