# Generated by Django 4.0.6 on 2022-09-27 12:43

from django.db import migrations, models

# nouveau
class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_recettedetailsanspesage_recettedetailpesage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recettedetailpesage',
            name='id_recette',
        ),
        migrations.AlterField(
            model_name='missions',
            name='motif',
            field=models.CharField(choices=[('Approvissionement', 'Approvissionement'), ('Livraison', 'Livraison')], default='Approvissionement', max_length=250),
        ),
    ]
