# Generated by Django 4.0.6 on 2022-09-27 12:57

from django.db import migrations, models
import django.utils.timezone
# nouveau

class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0010_recettedetailpesage_id_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recettedetailpesage',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='recettedetailpesage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
