# Generated by Django 4.1 on 2022-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenances", "0002_alter_infospieces_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="infospieces",
            constraint=models.UniqueConstraint(
                fields=("maintenanceConcernee", "nomPiece"),
                name="unique_id_maint_piece",
            ),
        ),
    ]
