# Generated by Django 4.1 on 2022-08-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0002_categorievehicules_depensemissions_docstransports_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicules",
            name="poids_vide",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
