# Generated by Django 4.1.1 on 2022-09-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercices", "0002_alter_exercices_date_exercice"),
        ("missions", "0003_alter_vehicules_poids_vide"),
    ]

    operations = [
        migrations.AddField(
            model_name="infodepensemissions",
            name="exercice",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="infoDepenseMission",
                to="exercices.exercices",
            ),
            preserve_default=False,
        ),
    ]
