# Generated by Django 4.1.1 on 2022-09-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercices", "0002_alter_exercices_date_exercice"),
        ("missions", "0004_infodepensemissions_exercice"),
    ]

    operations = [
        migrations.AddField(
            model_name="recettes",
            name="exercice",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="infoRecetteMission",
                to="exercices.exercices",
            ),
            preserve_default=False,
        ),
    ]
