# Generated by Django 4.1.1 on 2022-09-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0005_recettes_exercice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missions",
            name="motif",
            field=models.CharField(
                choices=[
                    ("Approvissionement", "Approvissionement"),
                    ("Livraision", "Livraison"),
                ],
                default="Approvissionement",
                max_length=250,
            ),
        ),
    ]
